before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS acts_as_many_tenants_test_tmp;create database IF NOT EXISTS acts_as_many_tenants_test;'; fi"
language: ruby
rvm:
  - 1.9.3
  - 1.8.7
env:
  - DB=sqlite
  - DB=mysql
  # - DB=postgres
